const columns = [
  'Profesor',
  'Correo',
  'Celular',
  'Fecha de Inicio',
  'Fecha de Fin',
  'Estado',
  'Acciones',
];

const dataSource = [
  {
    Profesor: 'Juan Peralta Rojas',
    Correo: 'jprojas@unprg.edu.pe',
    Celular: '987654321',
    'Fecha de Inicio': '18-02-2022',
    'Fecha de Fin': '19-02-2022',
    Estado: 'Programado',
    Acciones: 'true',
  },
  {
    Profesor: 'Pedro Cabrejos Rojas',
    Correo: 'pcrojas@unprg.edu.pe',
    Celular: '982357621',
    'Fecha de Inicio': '21-02-20',
    'Fecha de Fin': '22-02-2022',
    Estado: 'Programado',
    Acciones: 'true',
  },
  {
    Profesor: 'Luis Otake Malca',
    Correo: 'lomalca@unprg.edu.pe',
    Celular: '9324321',
    'Fecha de Inicio': '24-02-20',
    'Fecha de Fin': '25-02-2022',
    Estado: 'Reprogramado',
    Acciones: 'true',
  },
  {
    Profesor: 'Mateo Riojas Díaz',
    Correo: 'mrdiaz@unprg.edu.pe',
    Celular: '98642321',
    'Fecha de Inicio': '28-02-20',
    'Fecha de Fin': '01-03-2022',
    Estado: 'Programado',
    Acciones: 'true',
  },
  {
    Profesor: 'Lucia Rivas Aguero',
    Correo: 'lraguero@unprg.edu.pe',
    Celular: '973658254',
    'Fecha de Inicio': '22-02-20',
    'Fecha de Fin': '03-03-2022',
    Estado: 'Programado',
    Acciones: 'true',
  },
  {
    Profesor: 'Carlos Manuel Oblitas Rojas',
    Correo: 'cmorojas@unprg.edu.pe',
    Celular: '9463456781',
    'Fecha de Inicio': '18-02-20',
    'Fecha de Fin': '19-02-2022',
    Estado: 'Reprogramado',
    Acciones: 'true',
  },
  {
    Profesor: 'Marcos Peralta Portillas',
    Correo: 'mpportillas@unprg.edu.pe',
    Celular: '976234812',
    'Fecha de Inicio': '18-03-20',
    'Fecha de Fin': '19-03-2022',
    Estado: 'Programado',
    Acciones: 'true',
  },
  {
    Profesor: 'Ana Riojas Chambergo',
    Correo: 'archambergo@unprg.edu.pe',
    Celular: '978572347',
    'Fecha de Inicio': '28-03-20',
    'Fecha de Fin': '29-03-2022',
    Estado: 'Reprogramado',
    Acciones: 'true',
  },
  {
    Profesor: 'Rosa Rubio Pecsen',
    Correo: 'rrpecsen@unprg.edu.pe',
    Celular: '977369399',
    'Fecha de Inicio': '01-02-20',
    'Fecha de Fin': '03-02-2022',
    Estado: 'Reprogramado',
    Acciones: 'true',
  },
  {
    Profesor: 'Eduardo Toro Monsalve',
    Correo: 'etmonsalve@unprg.edu.pe',
    Celular: '965729586',
    'Fecha de Inicio': '05-02-20',
    'Fecha de Fin': '07-02-2022',
    Estado: 'Reprogramado',
    Acciones: 'true',
  },
];

export const ConstantsTaDa = {
  columns,
  dataSource,
};
