export const IconNames = {
  register: 'bi bi-pen',
  update: 'bi bi-pencil-square',
  delete: 'bi bi-trash',
  see: 'bi bi-eye',
  master: 'bi bi-file-ruled',
  doctorate: 'bi bi-file-ruled',
  course: 'bi bi-file-text',
  google: 'bi bi-google',
  success: 'bi bi-check',
  warning: 'bi bi-exclamation-lg',
  error: 'bi bi-x',
  confirm: 'bi bi-question',
  load: 'bi bi-arrow-repeat',
};
